[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "uvicorn fastapi_app:app --host 0.0.0.0 --port $PORT"
